// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvUFHvqgxbb3dMmNQQl4GL6rG2IILXEPY',
    appId: '1:651404915826:web:998649218bc7e8a2cd3eeb',
    messagingSenderId: '651404915826',
    projectId: 'e-commerce-57147',
    authDomain: 'e-commerce-57147.firebaseapp.com',
    storageBucket: 'e-commerce-57147.appspot.com',
    measurementId: 'G-N5S2F33WFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiZh7uUaljt50Xz_AOGX-m7ckMiqL8rGc',
    appId: '1:651404915826:android:b86e8fc3ded2a1bccd3eeb',
    messagingSenderId: '651404915826',
    projectId: 'e-commerce-57147',
    storageBucket: 'e-commerce-57147.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTQPK7XDIs6NFTLrxFYoxKkCjCTjDxVLo',
    appId: '1:651404915826:ios:9f4e118461e4fc41cd3eeb',
    messagingSenderId: '651404915826',
    projectId: 'e-commerce-57147',
    storageBucket: 'e-commerce-57147.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTQPK7XDIs6NFTLrxFYoxKkCjCTjDxVLo',
    appId: '1:651404915826:ios:009ead01a9f18874cd3eeb',
    messagingSenderId: '651404915826',
    projectId: 'e-commerce-57147',
    storageBucket: 'e-commerce-57147.appspot.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
